// Change business contact information only here when final details are available.
const AARVEX_CONFIG = { phone: '+919130218218', phoneDisplay: '+91 91302 18218', whatsapp: '919130218218', email: 'sales@aarvex.com', location: 'Pune, Maharashtra, India', web3formsAccessKey: '4a862c36-10db-40f3-8c12-791f44332520', whatsappMessage: 'Hello AARVEX, I would like to enquire about anchor/foundation bolts.' };
const navToggle = document.querySelector('.nav-toggle'); const primaryNav = document.querySelector('.primary-nav');
navToggle?.addEventListener('click', () => { const open = primaryNav.classList.toggle('is-open'); navToggle.setAttribute('aria-expanded', String(open)); });
primaryNav?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { primaryNav.classList.remove('is-open'); navToggle?.setAttribute('aria-expanded', 'false'); }));
document.querySelectorAll('[data-phone-text]').forEach((el) => { el.textContent = AARVEX_CONFIG.phoneDisplay; });
document.querySelectorAll('[data-phone-link]').forEach((el) => { el.href = `tel:${AARVEX_CONFIG.phone}`; });
document.querySelectorAll('[data-email-text]').forEach((el) => { el.textContent = AARVEX_CONFIG.email; }); document.querySelectorAll('[data-email-link]').forEach((el) => { el.href = `mailto:${AARVEX_CONFIG.email}`; }); document.querySelectorAll('[data-location]').forEach((el) => { el.textContent = AARVEX_CONFIG.location; }); document.querySelectorAll('[data-whatsapp-link]').forEach((el) => { el.href = `https://wa.me/${AARVEX_CONFIG.whatsapp}?text=${encodeURIComponent(AARVEX_CONFIG.whatsappMessage)}`; }); document.querySelector('#current-year').textContent = new Date().getFullYear();
const revealButton = document.querySelector('#reveal-phone'); const phoneDetails = document.querySelector('#phone-details'); revealButton?.addEventListener('click', () => { phoneDetails.hidden = false; revealButton.hidden = true; });
const form = document.querySelector('#enquiry-form'); const formError = document.querySelector('#form-error'); const formSuccess = document.querySelector('#form-success'); const submitButton = form?.querySelector('[type="submit"]'); form?.addEventListener('submit', async (event) => { event.preventDefault(); formSuccess.hidden = true; if (!form.checkValidity()) { formError.textContent = 'Please complete the required fields with valid details.'; formError.hidden = false; form.reportValidity(); return; } formError.hidden = true; submitButton.disabled = true; submitButton.textContent = 'Sending…'; try { const data = new FormData(form); data.append('access_key', AARVEX_CONFIG.web3formsAccessKey); data.append('subject', 'New AARVEX website enquiry'); data.append('from_name', 'AARVEX Website'); data.append('botcheck', ''); const response = await fetch('https://api.web3forms.com/submit', { method: 'POST', body: data, headers: { Accept: 'application/json' } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Submission failed.'); formSuccess.hidden = false; form.reset(); } catch (error) { formError.textContent = 'We could not send your enquiry. Please call or WhatsApp AARVEX instead.'; formError.hidden = false; } finally { submitButton.disabled = false; submitButton.innerHTML = 'Send Enquiry <span>→</span>'; } });
