// Change business contact information only here when final details are available.
const AARVEX_CONFIG = { phone: '+91XXXXXXXXXX', whatsapp: '91XXXXXXXXXX', email: 'sales@aarvex.com', location: 'Pune, Maharashtra, India', whatsappMessage: 'Hello AARVEX, I would like to enquire about anchor/foundation bolts.' };
const navToggle = document.querySelector('.nav-toggle'); const primaryNav = document.querySelector('.primary-nav');
navToggle?.addEventListener('click', () => { const open = primaryNav.classList.toggle('is-open'); navToggle.setAttribute('aria-expanded', String(open)); });
primaryNav?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { primaryNav.classList.remove('is-open'); navToggle?.setAttribute('aria-expanded', 'false'); }));
document.querySelectorAll('[data-phone-text]').forEach((el) => { el.textContent = AARVEX_CONFIG.phone.replace('XXXXXXXXXX', 'XXXXX XXXXX'); });
document.querySelectorAll('[data-phone-link]').forEach((el) => { el.href = `tel:${AARVEX_CONFIG.phone}`; });
document.querySelectorAll('[data-email-text]').forEach((el) => { el.textContent = AARVEX_CONFIG.email; }); document.querySelectorAll('[data-email-link]').forEach((el) => { el.href = `mailto:${AARVEX_CONFIG.email}`; }); document.querySelectorAll('[data-location]').forEach((el) => { el.textContent = AARVEX_CONFIG.location; }); document.querySelectorAll('[data-whatsapp-link]').forEach((el) => { el.href = `https://wa.me/${AARVEX_CONFIG.whatsapp}?text=${encodeURIComponent(AARVEX_CONFIG.whatsappMessage)}`; }); document.querySelector('#current-year').textContent = new Date().getFullYear();
const revealButton = document.querySelector('#reveal-phone'); const phoneDetails = document.querySelector('#phone-details'); revealButton?.addEventListener('click', () => { phoneDetails.hidden = false; revealButton.hidden = true; });
const form = document.querySelector('#enquiry-form'); const formError = document.querySelector('#form-error'); const formSuccess = document.querySelector('#form-success'); form?.addEventListener('submit', (event) => { event.preventDefault(); formSuccess.hidden = true; if (!form.checkValidity()) { formError.hidden = false; form.reportValidity(); return; } formError.hidden = true; formSuccess.hidden = false; form.reset(); });
